on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        if: ${{ github.ref_name == 'main' }}
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}

      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - name: CI
        run: yarn
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish
        run: yarn publish
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
